
import { MaintenanceActivity, RedTagData, SafetyAdvice } from './types';

export const MAINTENANCE_DATA: MaintenanceActivity[] = [
  { date: 8, line: "END TIE ROD 2 BP", activity: "PREVENTIVE", machine: "LA40, LA41, LA42, LA43", duration: "60 MINUTE", pic: "RULI, BILAL" },
  { date: 8, line: "END TIE ROD 2 FN", activity: "PREVENTIVE", machine: "ZMC03, ZMC05, ZMC06", duration: "90 MINUTE", pic: "RULI, BILAL" },
  { date: 8, line: "END TIE ROD 2 FN", activity: "PERBAIKAN MOTOR POMPA COOLANT", machine: "ZMC06", duration: "30 MINUTE", pic: "RULI, BILAL" },
  { date: 8, line: "BALLSTUD", activity: "GANTI HIDROLIK", machine: "AR04", duration: "60 MINUTE", pic: "CHOLIK" },
  { date: 12, line: "EXTENSION SHAFT", activity: "PREVENTIVE", machine: "AR08, ZMC01", duration: "60 MINUTE", pic: "ALY, BILAL" },
  { date: 12, line: "EXTENSION SHAFT", activity: "BATTERY CHANGE", machine: "ZMC01", duration: "30 MINUTE", pic: "ALY, BILAL" },
  { date: 12, line: "FORGING", activity: "PREVENTIVE", machine: "ACH01", duration: "30 MINUTE", pic: "AA, BILAL" },
  { date: 12, line: "END TIE ROD 1 FN", activity: "GANTI COOLANT", machine: "LA22, LA23", duration: "120 MINUTE", pic: "BILAL, BIMO, HARI, EPAN" },
  { date: 12, line: "END TIE ROD 1 FN", activity: "GANTI HIDROLIK", machine: "LA22, LA23", duration: "60 MINUTE", pic: "BILAL, BIMO, HARI, EPAN" },
  { date: 13, line: "INPUT SHAFT 1", activity: "PREVENTIVE", machine: "GP02", duration: "30 MINUTE", pic: "ALY, BILAL" },
  { date: 13, line: "INPUT SHAFT 2 BP", activity: "PREVENTIVE", machine: "LA14", duration: "60 MINUTE", pic: "ALY, BILAL" },
  { date: 13, line: "INPUT SHAFT 2 BP", activity: "GANTI HIDROLIK", machine: "LA-53", duration: "120 MINUTE", pic: "ALY, BILAL" },
  { date: 13, line: "INPUT SHAFT 2 FN", activity: "PREVENTIVE", machine: "GP04", duration: "60 MINUTE", pic: "ALY, BILAL" },
  { date: 14, line: "COUNTER SHAFT", activity: "PREVENTIVE", machine: "AR09, LA26, LA27, LA28, LA32, LA33, LA34, LA35, LA36", duration: "480 MINUTE", pic: "ALL MEMBER" },
  { date: 14, line: "COUNTER SHAFT", activity: "OVERHAULL", machine: "LA26, LA27, LA28", duration: "240 MINUTE", pic: "ALL MEMBER" },
  { date: 14, line: "COUNTER SHAFT", activity: "PERBAIKAN PINTU", machine: "LA34", duration: "60 MINUTE", pic: "ALL MEMBER" },
  { date: 14, line: "UPPER SHAFT", activity: "GANTI COOLANT", machine: "LA06", duration: "120 MINUTE", pic: "ALWI, CHANDRA" },
  { date: 14, line: "UPPER SHAFT", activity: "GANTI HIDROLIK", machine: "LA06", duration: "60 MINUTE", pic: "ALWI, CHANDRA" },
  { date: 15, line: "PINION STEERING 1", activity: "GANTI COOLANT", machine: "LA07, LA37, LA38", duration: "120 MINUTE", pic: "BIMO, CHOLIK, HARI, EPAN, ALWI, CHANDRA" },
  { date: 15, line: "PINION STEERING 1", activity: "GANTI HIDROLIK", machine: "LA38", duration: "60 MINUTE", pic: "BIMO, CHOLIK, HARI, EPAN, ALWI, CHANDRA" },
  { date: 19, line: "INDUCTION", activity: "GANTI COOLANT", machine: "HF01, HF 02", duration: "480 MINUTE", pic: "ALL MEMBER" },
  { date: 19, line: "SOCKET 1", activity: "GANTI COOLANT", machine: "LA09", duration: "120 MINUTE", pic: "CHOLIK, CHANDRA" },
  { date: 20, line: "PINION STEERING 1", activity: "PREVENTIVE", machine: "AR02", duration: "30 MINUTE", pic: "ALY, ALWI" },
  { date: 20, line: "PINION STEERING 2", activity: "PREVENTIVE", machine: "AR11", duration: "30 MINUTE", pic: "ALY, ALWI" },
  { date: 20, line: "TIE ROD 2", activity: "GANTI HIDROLIK", machine: "LA44", duration: "60 MINUTE", pic: "BIMO" },
  { date: 21, line: "ROLLING INPUT SHAFT", activity: "PREVENTIVE", machine: "AR05", duration: "30 MINUTE", pic: "ALY, ALWI" },
  { date: 21, line: "LOWER SHAFT", activity: "GANTI COOLANT", machine: "LA04", duration: "120 MINUTE", pic: "BIMO, CHANDRA" },
  { date: 22, line: "SOCKET 1", activity: "PREVENTIVE", machine: "LA09, LA03", duration: "60 MINUTE", pic: "RULI, CHOLIK" },
  { date: 22, line: "SOCKET 1", activity: "PENANGANAN AIR LEAK", machine: "AR03", duration: "60 MINUTE", pic: "RULI, CHOLIK" },
  { date: 22, line: "SOCKET 2", activity: "PREVENTIVE", machine: "AR06", duration: "30 MINUTE", pic: "RULI, CHOLIK" },
  { date: 22, line: "LOWER SHAFT", activity: "GANTI COOLANT", machine: "LA01, LA02, LA03", duration: "120 MINUTE", pic: "ALWI, CHOLIK, HARI, CHANDRA, BILAL, EPAN" },
  { date: 22, line: "LOWER SHAFT", activity: "GANTI HIDROLIK", machine: "LA01, LA02", duration: "120 MINUTE", pic: "ALWI, CHOLIK, HARI, CHANDRA, BILAL, EPAN" },
  { date: 26, line: "TIE ROD 1 FN", activity: "PREVENTIVE", machine: "AR06", duration: "30 MINUTE", pic: "RULI, CHOLIK" },
  { date: 26, line: "TIE ROD 2", activity: "PREVENTIVE", machine: "LA44, LA45, LA46", duration: "90 MINUTE", pic: "RULI, CHOLIK" },
  { date: 26, line: "TIE ROD 2", activity: "GANTI HMI", machine: "LA46", duration: "60 MINUTE", pic: "RULI, CHOLIK" },
  { date: 26, line: "INPUT SHAFT 1 FN", activity: "GANTI COOLANT", machine: "GP02", duration: "120 MINUTE", pic: "BILAL, EPAN" },
  { date: 26, line: "INPUT SHAFT 1 FN", activity: "GANTI HIDROLIK", machine: "GP02", duration: "60 MINUTE", pic: "BILAL, EPAN" },
  { date: 26, line: "END TIE ROD 2 BP", activity: "GANTI COOLANT", machine: "LA40", duration: "120 MINUTE", pic: "ALWI, HARI" },
  { date: 26, line: "END TIE ROD 2 BP", activity: "GANTI HIDROLIK", machine: "LA40", duration: "60 MINUTE", pic: "ALWI, HARI" },
  { date: 27, line: "UPPER SHAFT", activity: "PREVENTIVE", machine: "AR12, GP03, LA51, LA52", duration: "240 MINUTE", pic: "ALY, ALWI" },
  { date: 27, line: "UPPER SHAFT", activity: "PEMERIKSAAN LUBRIKASI", machine: "LA51", duration: "30 MINUTE", pic: "ALY, ALWI" },
  { date: 27, line: "END TIE ROD 2 BP", activity: "GANTI COOLANT", machine: "LA41,LA42,LA43", duration: "120 MINUTE", pic: "CHOLIK, BILAL, HARI, EPAN, BIMO, CHANDRA" },
  { date: 27, line: "END TIE ROD 2 BP", activity: "GANTI HIDROLIK", machine: "LA41,LA42,LA43", duration: "120 MINUTE", pic: "CHOLIK, BILAL, HARI, EPAN, BIMO, CHANDRA" },
  { date: 28, line: "BALLSTUD", activity: "PREVENTIVE", machine: "AR04", duration: "30 MINUTE", pic: "RULI, CHOLIK" },
  { date: 28, line: "LOWER SHAFT", activity: "PREVENTIVE", machine: "LA01, LA02, LA03, LA04, LA05, AR01, GP01", duration: "90 MINUTE", pic: "ALY, ALWI" },
  { date: 28, line: "LOWER SHAFT", activity: "BATTERY CHANGE", machine: "LA01, LA02, LA03, LA04, LA05", duration: "60 MINUTE", pic: "ALY, ALWI" },
  { date: 28, line: "INPUT SHAFT 2 FN", activity: "GANTI COOLANT", machine: "GP04", duration: "120 MINUTE", pic: "ALWI, EPAN" },
  { date: 28, line: "INPUT SHAFT 2 FN", activity: "GANTI HIDROLIK", machine: "GP04", duration: "60 MINUTE", pic: "ALWI, EPAN" },
  { date: 28, line: "PINION STEERING 2", activity: "GANTI COOLANT", machine: "LA47", duration: "120 MINUTE", pic: "CHOLIK, HARI" },
  { date: 28, line: "PINION STEERING 2", activity: "GANTI HIDROLIK", machine: "LA47", duration: "60 MINUTE", pic: "CHOLIK, HARI" },
  { date: 29, line: "PINION STEERING 2", activity: "GANTI COOLANT", machine: "LA49, LA55, LA57", duration: "120 MINUTE", pic: "BILAL, ALWI, EPAN, HARI, BIMO, CHANDRA" },
  { date: 29, line: "PINION STEERING 2", activity: "GANTI HIDROLIK", machine: "LA55", duration: "60 MINUTE", pic: "BILAL, ALWI, EPAN, HARI, BIMO, CHANDRA" },
];

export const RED_TAG_DATA: RedTagData[] = [
  { month: "JAN", masuk: 18, selesai: 18, totalMasuk: 18, totalSelesai: 18, sisa: 0, percentage: "100.00%" },
  { month: "FEB", masuk: 10, selesai: 10, totalMasuk: 28, totalSelesai: 28, sisa: 0, percentage: "100.00%" },
  { month: "MAR", masuk: 10, selesai: 10, totalMasuk: 38, totalSelesai: 38, sisa: 0, percentage: "100.00%" },
  { month: "APR", masuk: 2, selesai: 2, totalMasuk: 40, totalSelesai: 40, sisa: 0, percentage: "100.00%" },
  { month: "MAY", masuk: 7, selesai: 6, totalMasuk: 47, totalSelesai: 46, sisa: 1, percentage: "97.87%" },
  { month: "JUN", masuk: 12, selesai: 12, totalMasuk: 59, totalSelesai: 58, sisa: 1, percentage: "98.31%" },
  { month: "JUL", masuk: 11, selesai: 11, totalMasuk: 70, totalSelesai: 69, sisa: 1, percentage: "98.57%" },
  { month: "AUG", masuk: 11, selesai: 11, totalMasuk: 81, totalSelesai: 80, sisa: 1, percentage: "98.77%" },
  { month: "SEP", masuk: 17, selesai: 16, totalMasuk: 98, totalSelesai: 96, sisa: 2, percentage: "97.96%" },
  { month: "OCT", masuk: 14, selesai: 12, totalMasuk: 112, totalSelesai: 108, sisa: 4, percentage: "96.43%" },
  { month: "NOV", masuk: 4, selesai: 4, totalMasuk: 116, totalSelesai: 112, sisa: 4, percentage: "96.55%" },
  { month: "DEC", masuk: 2, selesai: 1, totalMasuk: 118, totalSelesai: 113, sisa: 5, percentage: "95.76%" },
];

export const SAFETY_ADVICES: SafetyAdvice[] = [
  { id: 1, text: "tunjuk kanan kiri saat melewati persimpangan" },
  { id: 2, text: "jangan menggunakan handphone saat berjalan" },
  { id: 3, text: "jangan memasukan tangan kedalam saku saat berjalan" },
  { id: 4, text: "jangan merokok di sembarang tempat" },
  { id: 5, text: "pegang hand rail saat menaiki tangga" },
  { id: 6, text: "berjalan pada jalur yang sudah dibuat" },
];
